// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9ZGqdpHtcdD2lHIw-FViYxmH98c7UXk',
    appId: '1:221008081019:web:d7fe9c42bcd654a0e332de',
    messagingSenderId: '221008081019',
    projectId: 'gas-system-1b341',
    authDomain: 'gas-system-1b341.firebaseapp.com',
    storageBucket: 'gas-system-1b341.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0M2Uf0VQ9iAG9plmF_pHX8RITXXCnYs0',
    appId: '1:221008081019:android:c9173a5e6d78998ce332de',
    messagingSenderId: '221008081019',
    projectId: 'gas-system-1b341',
    storageBucket: 'gas-system-1b341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1qekHMQXngBGB6a4xiX6nFYijvp6hfc',
    appId: '1:221008081019:ios:250357e526fc6ed4e332de',
    messagingSenderId: '221008081019',
    projectId: 'gas-system-1b341',
    storageBucket: 'gas-system-1b341.firebasestorage.app',
    iosBundleId: 'com.example.gasUserApp',
  );
}
